settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: renhotec
    name: Renhotec
    url: 'https://www.renhotec.com/'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: renhotecev
    name: Renhotec EV
    url: 'https://www.renhotecev.com/'
    method: GET
    expectStatus: 200

  - id: renhotecpro
    name: Renhotec Pro
    url: 'https://renhotecpro.com/'
    method: GET
    expectStatus: 200

  - id: renhotecrf
    name: Renhotec RF
    url: 'https://www.renhotecrf.com/'
    method: GET
    expectStatus: 200

  - id: renhotec-industrial
    name: Renhotec Industrial
    url: 'https://renhotec-industrial.com/'
    method: GET
    expectStatus: 200

  - id: elecpeek
    name: Renhotec Elecpeek
    url: 'https://www.elecpeek.com/'
    method: GET
    expectStatus: 200

  - id: metabee
    name: Metabee
    url: 'https://www.metabee.com/'
    method: GET
    expectStatus: 200

  - id: elecbee
    name: Elecbee
    url: 'https://www.elecbee.com/'
    method: GET
    expectStatus: 200

  - id: ebee
    name: Ebee
    url: 'https://www.ebee.com/'
    method: GET
    expectStatus: 200
